# Generated by Django 5.2.7 on 2025-10-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Assinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinantes', to='notificacoes.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True)),
                ('inicio_previsto', models.DateTimeField()),
                ('fim_previsto', models.DateTimeField()),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('normalizado', 'Normalizado'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='notificacoes.bairro')),
            ],
            options={
                'ordering': ['-inicio_previsto'],
            },
        ),
        migrations.CreateModel(
            name='LogEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=255)),
                ('canal', models.CharField(max_length=30)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('tentativa', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(default='alerta', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notificacoes.evento')),
            ],
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['bairro', 'inicio_previsto', 'status'], name='notificacoe_bairro__1654b5_idx'),
        ),
        migrations.AddIndex(
            model_name='logenvio',
            index=models.Index(fields=['evento', 'destinatario', 'tipo'], name='notificacoe_evento__c45b69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='logenvio',
            unique_together={('evento', 'destinatario', 'tipo', 'tentativa')},
        ),
    ]
